import { AnalysisResult } from '@/types'

export const mockAnalysisResults: AnalysisResult[] = [
  {
    id: 'analysis-1',
    content_id: 'content-1',
    labels: [
      { description: 'Mountain', score: 0.95 },
      { description: 'Landscape', score: 0.92 },
      { description: 'Nature', score: 0.88 },
      { description: 'Sky', score: 0.85 },
    ],
    texts: ['성산일출봉', 'Seongsan Ilchulbong'],
    full_matching_images: ['https://example.com/match1.jpg', 'https://example.com/match2.jpg'],
    partial_matching_images: ['https://example.com/partial1.jpg'],
    similar_images: [],
    analyzed_at: '2025-03-05T10:15:00Z',
  },
  {
    id: 'analysis-2',
    content_id: 'content-2',
    labels: [
      { description: 'Beach', score: 0.97 },
      { description: 'Ocean', score: 0.94 },
      { description: 'Summer', score: 0.89 },
      { description: 'Vacation', score: 0.82 },
    ],
    texts: ['해운대', 'Haeundae Beach'],
    full_matching_images: [
      'https://example.com/beach1.jpg',
      'https://example.com/beach2.jpg',
      'https://example.com/beach3.jpg',
    ],
    partial_matching_images: [
      'https://example.com/beach-partial1.jpg',
      'https://example.com/beach-partial2.jpg',
    ],
    similar_images: [],
    analyzed_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'analysis-3',
    content_id: 'content-3',
    labels: [
      { description: 'Temple', score: 0.93 },
      { description: 'Architecture', score: 0.9 },
      { description: 'Buddhism', score: 0.87 },
    ],
    texts: ['불국사', 'Bulguksa Temple'],
    full_matching_images: ['https://example.com/temple1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-04-12T11:30:00Z',
  },
  {
    id: 'analysis-4',
    content_id: 'content-4',
    labels: [
      { description: 'Eiffel Tower', score: 0.98 },
      { description: 'Paris', score: 0.96 },
      { description: 'Landmark', score: 0.94 },
      { description: 'France', score: 0.91 },
    ],
    texts: ['Tour Eiffel', 'Paris'],
    full_matching_images: [
      'https://example.com/eiffel1.jpg',
      'https://example.com/eiffel2.jpg',
      'https://example.com/eiffel3.jpg',
      'https://example.com/eiffel4.jpg',
    ],
    partial_matching_images: [
      'https://example.com/eiffel-partial1.jpg',
      'https://example.com/eiffel-partial2.jpg',
      'https://example.com/eiffel-partial3.jpg',
      'https://example.com/eiffel-partial4.jpg',
    ],
    similar_images: [],
    analyzed_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'analysis-5',
    content_id: 'content-5',
    labels: [
      { description: 'Big Ben', score: 0.96 },
      { description: 'London', score: 0.93 },
      { description: 'Clock Tower', score: 0.9 },
    ],
    texts: ['Big Ben', 'Westminster'],
    full_matching_images: ['https://example.com/bigben1.jpg', 'https://example.com/bigben2.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-05-22T10:45:00Z',
  },
  {
    id: 'analysis-6',
    content_id: 'content-7',
    labels: [
      { description: 'Tokyo Skytree', score: 0.97 },
      { description: 'Tokyo', score: 0.95 },
      { description: 'Tower', score: 0.92 },
    ],
    texts: ['スカイツリー', 'Tokyo Skytree'],
    full_matching_images: ['https://example.com/skytree1.jpg', 'https://example.com/skytree2.jpg'],
    partial_matching_images: [
      'https://example.com/skytree-partial1.jpg',
      'https://example.com/skytree-partial2.jpg',
    ],
    similar_images: [],
    analyzed_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'analysis-7',
    content_id: 'content-8',
    labels: [
      { description: 'Sydney Opera House', score: 0.99 },
      { description: 'Sydney', score: 0.96 },
      { description: 'Architecture', score: 0.93 },
    ],
    texts: ['Sydney Opera House'],
    full_matching_images: [
      'https://example.com/opera1.jpg',
      'https://example.com/opera2.jpg',
      'https://example.com/opera3.jpg',
    ],
    partial_matching_images: [
      'https://example.com/opera-partial1.jpg',
      'https://example.com/opera-partial2.jpg',
      'https://example.com/opera-partial3.jpg',
    ],
    similar_images: [],
    analyzed_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'analysis-8',
    content_id: 'content-9',
    labels: [
      { description: 'Gondola', score: 0.94 },
      { description: 'Venice', score: 0.92 },
      { description: 'Canal', score: 0.89 },
    ],
    texts: ['Venezia', 'Gondola'],
    full_matching_images: ['https://example.com/venice1.jpg', 'https://example.com/venice2.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-07-15T12:00:00Z',
  },
  {
    id: 'analysis-9',
    content_id: 'content-11',
    labels: [
      { description: 'Sagrada Familia', score: 0.98 },
      { description: 'Barcelona', score: 0.95 },
      { description: 'Church', score: 0.91 },
    ],
    texts: ['Sagrada Família', 'Gaudí'],
    full_matching_images: ['https://example.com/sagrada1.jpg', 'https://example.com/sagrada2.jpg'],
    partial_matching_images: ['https://example.com/sagrada-partial1.jpg'],
    similar_images: [],
    analyzed_at: '2025-08-10T11:00:00Z',
  },
  {
    id: 'analysis-10',
    content_id: 'content-12',
    labels: [
      { description: 'Prague', score: 0.93 },
      { description: 'Old Town Square', score: 0.9 },
      { description: 'Architecture', score: 0.88 },
    ],
    texts: ['Praha', 'Old Town'],
    full_matching_images: ['https://example.com/prague1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-09-05T13:45:00Z',
  },
  {
    id: 'analysis-11',
    content_id: 'content-14',
    labels: [
      { description: 'Smartphone', score: 0.96 },
      { description: 'Technology', score: 0.92 },
      { description: 'Electronics', score: 0.89 },
    ],
    texts: [],
    full_matching_images: ['https://example.com/phone1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-05-25T10:00:00Z',
  },
  {
    id: 'analysis-12',
    content_id: 'content-17',
    labels: [
      { description: 'Smartwatch', score: 0.95 },
      { description: 'Wearable', score: 0.91 },
      { description: 'Technology', score: 0.88 },
    ],
    texts: [],
    full_matching_images: ['https://example.com/watch1.jpg', 'https://example.com/watch2.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-07-20T10:30:00Z',
  },
  {
    id: 'analysis-13',
    content_id: 'content-19',
    labels: [
      { description: 'Tablet', score: 0.94 },
      { description: 'Screen', score: 0.9 },
      { description: 'Display', score: 0.87 },
    ],
    texts: [],
    full_matching_images: ['https://example.com/tablet1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-09-10T11:30:00Z',
  },
  {
    id: 'analysis-14',
    content_id: 'content-22',
    labels: [
      { description: 'Poster', score: 0.92 },
      { description: 'Design', score: 0.89 },
      { description: 'Art', score: 0.85 },
    ],
    texts: ['EXHIBITION', '2025'],
    full_matching_images: ['https://example.com/poster1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-04-20T14:45:00Z',
  },
  {
    id: 'analysis-15',
    content_id: 'content-26',
    labels: [
      { description: 'Event', score: 0.91 },
      { description: 'Celebration', score: 0.88 },
      { description: 'People', score: 0.85 },
    ],
    texts: ['10th Anniversary'],
    full_matching_images: ['https://example.com/event1.jpg', 'https://example.com/event2.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-06-25T16:45:00Z',
  },
  {
    id: 'analysis-16',
    content_id: 'content-27',
    labels: [
      { description: 'Product Launch', score: 0.93 },
      { description: 'Presentation', score: 0.89 },
      { description: 'Conference', score: 0.86 },
    ],
    texts: ['NEW PRODUCT'],
    full_matching_images: ['https://example.com/launch1.jpg'],
    partial_matching_images: [],
    similar_images: [],
    analyzed_at: '2025-08-30T11:00:00Z',
  },
]
