import { DetectedContent } from '@/types'

// DB 스키마와 일치하는 Mock Detected Contents 데이터
export const mockDetectedContents: DetectedContent[] = [
  // content-1 의 발견 콘텐츠 (3개)
  {
    id: 'detected-1',
    content_id: 'content-1',
    source_url: 'https://example.com/travel/jeju-seongsan',
    image_url: 'https://example.com/images/jeju_similar_1.jpg',
    page_title: 'Jeju Island Travel Guide - Seongsan Ilchulbong',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-06T09:00:00Z',
    created_at: '2024-03-05T10:15:00Z',
  },
  {
    id: 'detected-2',
    content_id: 'content-1',
    source_url: 'https://tourism.go.kr/jeju/seongsan',
    image_url: 'https://tourism.go.kr/images/seongsan_sunrise.jpg',
    page_title: '성산일출봉 - 한국관광공사',
    detection_type: 'partial',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-06T09:05:00Z',
    created_at: '2024-03-05T10:15:00Z',
  },
  {
    id: 'detected-3',
    content_id: 'content-1',
    source_url: null,
    image_url: 'https://cdn.example.com/travel_images/jeju_mountain.jpg',
    page_title: null,
    detection_type: 'similar',
    admin_review_status: 'no_match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-06T09:10:00Z',
    created_at: '2024-03-05T10:15:00Z',
  },

  // content-2 의 발견 콘텐츠 (5개)
  {
    id: 'detected-4',
    content_id: 'content-2',
    source_url: 'https://visitbusan.net/haeundae-beach',
    image_url: 'https://visitbusan.net/images/haeundae_summer.jpg',
    page_title: 'Haeundae Beach - Visit Busan',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-09T10:00:00Z',
    created_at: '2024-03-08T15:00:00Z',
  },
  {
    id: 'detected-5',
    content_id: 'content-2',
    source_url: 'https://travel-blog.com/busan-beaches',
    image_url: 'https://travel-blog.com/uploads/haeundae_2024.jpg',
    page_title: 'Best Beaches in Busan 2024',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-09T10:05:00Z',
    created_at: '2024-03-08T15:00:00Z',
  },
  {
    id: 'detected-6',
    content_id: 'content-2',
    source_url: 'https://koreatourism.or.kr/busan',
    image_url: 'https://koreatourism.or.kr/images/busan_beach.jpg',
    page_title: '부산 해운대 - 한국 관광 정보',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-03-08T15:00:00Z',
  },
  {
    id: 'detected-7',
    content_id: 'content-2',
    source_url: 'https://photogallery.com/beaches/korea',
    image_url: 'https://photogallery.com/img/korean_beach_01.jpg',
    page_title: 'Korean Beach Photography Gallery',
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-03-08T15:00:00Z',
  },
  {
    id: 'detected-8',
    content_id: 'content-2',
    source_url: null,
    image_url: 'https://images.cdn.com/random_beach_123.jpg',
    page_title: null,
    detection_type: 'similar',
    admin_review_status: 'cannot_compare',
    reviewed_by: 'user-1',
    reviewed_at: '2024-03-09T10:15:00Z',
    created_at: '2024-03-08T15:00:00Z',
  },

  // content-3 의 발견 콘텐츠 (1개)
  {
    id: 'detected-9',
    content_id: 'content-3',
    source_url: 'https://heritage.go.kr/bulguksa',
    image_url: 'https://heritage.go.kr/images/bulguksa_autumn.jpg',
    page_title: '불국사 - 문화재청',
    detection_type: 'partial',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-04-13T10:00:00Z',
    created_at: '2024-04-12T11:30:00Z',
  },

  // content-4 의 발견 콘텐츠 (8개)
  {
    id: 'detected-10',
    content_id: 'content-4',
    source_url: 'https://parisinfo.com/eiffel-tower',
    image_url: 'https://parisinfo.com/media/eiffel_tower_2024.jpg',
    page_title: 'Eiffel Tower - Paris Official Website',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-21T09:00:00Z',
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-11',
    content_id: 'content-4',
    source_url: 'https://toureiffel.paris/en',
    image_url: 'https://toureiffel.paris/images/tower_view.jpg',
    page_title: 'Official Eiffel Tower Website',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-21T09:05:00Z',
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-12',
    content_id: 'content-4',
    source_url: 'https://wikipedia.org/wiki/Eiffel_Tower',
    image_url: 'https://upload.wikimedia.org/eiffel_tower.jpg',
    page_title: 'Eiffel Tower - Wikipedia',
    detection_type: 'partial',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-21T09:10:00Z',
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-13',
    content_id: 'content-4',
    source_url: 'https://travelguide.paris/landmarks',
    image_url: 'https://travelguide.paris/img/eiffel_day.jpg',
    page_title: 'Paris Landmarks Guide 2024',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-21T09:15:00Z',
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-14',
    content_id: 'content-4',
    source_url: 'https://photoparis.com/gallery/eiffel',
    image_url: 'https://photoparis.com/uploads/eiffel_photo_01.jpg',
    page_title: 'Eiffel Tower Photo Gallery',
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-15',
    content_id: 'content-4',
    source_url: 'https://instaparis.fr/eiffel-moments',
    image_url: 'https://instaparis.fr/media/eiffel_sunset.jpg',
    page_title: 'Best Instagram Spots - Eiffel Tower',
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-16',
    content_id: 'content-4',
    source_url: null,
    image_url: 'https://cdn.stockphotos.com/paris_tower_123.jpg',
    page_title: null,
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-05-20T17:20:00Z',
  },
  {
    id: 'detected-17',
    content_id: 'content-4',
    source_url: 'https://europetravelguide.com/paris',
    image_url: 'https://europetravelguide.com/img/paris_eiffel.jpg',
    page_title: 'Paris Travel Guide - Must See Attractions',
    detection_type: 'partial',
    admin_review_status: 'no_match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-21T09:30:00Z',
    created_at: '2024-05-20T17:20:00Z',
  },

  // content-5 의 발견 콘텐츠 (2개)
  {
    id: 'detected-18',
    content_id: 'content-5',
    source_url: 'https://visitlondon.com/big-ben',
    image_url: 'https://visitlondon.com/images/big_ben_tower.jpg',
    page_title: 'Big Ben - Visit London',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-23T10:00:00Z',
    created_at: '2024-05-22T10:45:00Z',
  },
  {
    id: 'detected-19',
    content_id: 'content-5',
    source_url: 'https://parliament.uk/big-ben',
    image_url: 'https://parliament.uk/media/clock_tower.jpg',
    page_title: 'The Elizabeth Tower (Big Ben) - UK Parliament',
    detection_type: 'partial',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-05-23T10:05:00Z',
    created_at: '2024-05-22T10:45:00Z',
  },

  // content-7 의 발견 콘텐츠 (2개)
  {
    id: 'detected-20',
    content_id: 'content-7',
    source_url: 'https://similarad.com/promotions/sale-banner',
    image_url: 'https://similarad.com/images/sale_50_banner.jpg',
    page_title: 'Similar Sale Promotion Banner Designs',
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-02-15T10:30:00Z',
  },
  {
    id: 'detected-21',
    content_id: 'content-7',
    source_url: null,
    image_url: 'https://cdn.adplatform.com/banner_promo_001.png',
    page_title: null,
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-02-15T10:30:00Z',
  },

  // content-8 의 발견 콘텐츠 (1개)
  {
    id: 'detected-22',
    content_id: 'content-8',
    source_url: 'https://designinspiration.com/launch-posters',
    image_url: 'https://designinspiration.com/uploads/poster_launch_2024.jpg',
    page_title: 'Product Launch Poster Design Inspiration',
    detection_type: 'similar',
    admin_review_status: 'no_match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-02-19T10:00:00Z',
    created_at: '2024-02-18T15:00:00Z',
  },

  // content-17 의 발견 콘텐츠 (1개)
  {
    id: 'detected-23',
    content_id: 'content-17',
    source_url: 'https://exhibitionarchive.com/poster-designs',
    image_url: 'https://exhibitionarchive.com/images/exhibition_poster_2024.jpg',
    page_title: 'Exhibition Poster Designs Archive',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-04-20T14:45:00Z',
  },

  // content-18 의 발견 콘텐츠 (2개)
  {
    id: 'detected-24',
    content_id: 'content-18',
    source_url: 'https://eventphotos.com/corporate-events',
    image_url: 'https://eventphotos.com/img/anniversary_celebration.jpg',
    page_title: 'Corporate Anniversary Event Photos',
    detection_type: 'similar',
    admin_review_status: 'match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-06-26T09:00:00Z',
    created_at: '2024-06-25T16:45:00Z',
  },
  {
    id: 'detected-25',
    content_id: 'content-18',
    source_url: null,
    image_url: 'https://cdn.stockevents.com/event_celebration_456.jpg',
    page_title: null,
    detection_type: 'similar',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-06-25T16:45:00Z',
  },

  // content-19 의 발견 콘텐츠 (1개)
  {
    id: 'detected-26',
    content_id: 'content-19',
    source_url: 'https://productlaunchevents.com/tech-launches',
    image_url: 'https://productlaunchevents.com/images/tech_launch_2024.jpg',
    page_title: 'Tech Product Launch Events 2024',
    detection_type: 'similar',
    admin_review_status: 'no_match',
    reviewed_by: 'user-1',
    reviewed_at: '2024-08-31T10:00:00Z',
    created_at: '2024-08-30T11:00:00Z',
  },
]

// Helper function to get detected contents by content
export const getDetectedContentsByContent = (contentId: string): DetectedContent[] => {
  return mockDetectedContents.filter((detected) => detected.content_id === contentId)
}

// Helper function to get detected content count by content
export const getDetectedContentCount = (contentId: string): number => {
  return mockDetectedContents.filter((detected) => detected.content_id === contentId).length
}

// Helper function to get detected contents by review status
export const getDetectedContentsByStatus = (status: string): DetectedContent[] => {
  return mockDetectedContents.filter((detected) => detected.admin_review_status === status)
}

// Helper function to get detected content by id
export const getDetectedContentById = (id: string): DetectedContent | undefined => {
  return mockDetectedContents.find((detected) => detected.id === id)
}
