import { DetectedContent } from '@/types'

export const mockDetectedContents: DetectedContent[] = [
  // Content 1 발견 결과 (3건)
  {
    id: 'detected-1',
    original_content_id: 'content-1',
    detected_url: 'https://example.com/detected/seongsan1.jpg',
    similarity_score: 0.98,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-06T09:00:00Z',
    review_note: '동일한 이미지 확인',
    detected_at: '2025-03-05T10:15:00Z',
  },
  {
    id: 'detected-2',
    original_content_id: 'content-1',
    detected_url: 'https://example.com/detected/seongsan2.jpg',
    similarity_score: 0.87,
    detection_type: 'partial',
    review_status: 'no_match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-06T09:10:00Z',
    review_note: '부분적으로 유사하나 다른 각도',
    detected_at: '2025-03-05T10:15:00Z',
  },
  {
    id: 'detected-3',
    original_content_id: 'content-1',
    detected_url: 'https://example.com/detected/seongsan3.jpg',
    similarity_score: 0.75,
    detection_type: 'similar',
    review_status: 'unclear',
    review_note: '추가 검토 필요',
    detected_at: '2025-03-05T10:15:00Z',
  },

  // Content 2 발견 결과 (5건)
  {
    id: 'detected-4',
    original_content_id: 'content-2',
    detected_url: 'https://example.com/detected/beach1.jpg',
    similarity_score: 0.99,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-08T16:00:00Z',
    review_note: '완전 일치',
    detected_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-5',
    original_content_id: 'content-2',
    detected_url: 'https://example.com/detected/beach2.jpg',
    similarity_score: 0.96,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-08T16:05:00Z',
    review_note: '크기만 다름',
    detected_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-6',
    original_content_id: 'content-2',
    detected_url: 'https://example.com/detected/beach3.jpg',
    similarity_score: 0.92,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-7',
    original_content_id: 'content-2',
    detected_url: 'https://example.com/detected/beach-partial1.jpg',
    similarity_score: 0.84,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-8',
    original_content_id: 'content-2',
    detected_url: 'https://example.com/detected/beach-partial2.jpg',
    similarity_score: 0.78,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-03-08T15:00:00Z',
  },

  // Content 3 발견 결과 (1건)
  {
    id: 'detected-9',
    original_content_id: 'content-3',
    detected_url: 'https://example.com/detected/temple1.jpg',
    similarity_score: 0.89,
    detection_type: 'full',
    review_status: 'no_match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-04-13T10:00:00Z',
    review_note: '다른 계절에 촬영된 것으로 보임',
    detected_at: '2025-04-12T11:30:00Z',
  },

  // Content 4 발견 결과 (8건)
  {
    id: 'detected-10',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel1.jpg',
    similarity_score: 0.97,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-21T09:00:00Z',
    review_note: '동일 이미지',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-11',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel2.jpg',
    similarity_score: 0.95,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-21T09:05:00Z',
    review_note: '워터마크 제거된 버전',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-12',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel3.jpg',
    similarity_score: 0.93,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-13',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel4.jpg',
    similarity_score: 0.9,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-14',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel-partial1.jpg',
    similarity_score: 0.85,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-15',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel-partial2.jpg',
    similarity_score: 0.82,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-16',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel-partial3.jpg',
    similarity_score: 0.79,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-17',
    original_content_id: 'content-4',
    detected_url: 'https://example.com/detected/eiffel-partial4.jpg',
    similarity_score: 0.76,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-05-20T17:20:00Z',
  },

  // Content 5 발견 결과 (2건)
  {
    id: 'detected-18',
    original_content_id: 'content-5',
    detected_url: 'https://example.com/detected/bigben1.jpg',
    similarity_score: 0.91,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-22T11:30:00Z',
    review_note: '일치',
    detected_at: '2025-05-22T10:45:00Z',
  },
  {
    id: 'detected-19',
    original_content_id: 'content-5',
    detected_url: 'https://example.com/detected/bigben2.jpg',
    similarity_score: 0.88,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-05-22T10:45:00Z',
  },

  // Content 7 발견 결과 (4건)
  {
    id: 'detected-20',
    original_content_id: 'content-7',
    detected_url: 'https://example.com/detected/skytree1.jpg',
    similarity_score: 0.94,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-21',
    original_content_id: 'content-7',
    detected_url: 'https://example.com/detected/skytree2.jpg',
    similarity_score: 0.91,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-22',
    original_content_id: 'content-7',
    detected_url: 'https://example.com/detected/skytree-partial1.jpg',
    similarity_score: 0.83,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-23',
    original_content_id: 'content-7',
    detected_url: 'https://example.com/detected/skytree-partial2.jpg',
    similarity_score: 0.77,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-06-15T09:45:00Z',
  },

  // Content 8 발견 결과 (6건)
  {
    id: 'detected-24',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera1.jpg',
    similarity_score: 0.99,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-07-02T10:00:00Z',
    review_note: '완전 동일',
    detected_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-25',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera2.jpg',
    similarity_score: 0.96,
    detection_type: 'full',
    review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-07-02T10:05:00Z',
    review_note: '색보정 버전',
    detected_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-26',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera3.jpg',
    similarity_score: 0.93,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-27',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera-partial1.jpg',
    similarity_score: 0.86,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-28',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera-partial2.jpg',
    similarity_score: 0.81,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-29',
    original_content_id: 'content-8',
    detected_url: 'https://example.com/detected/opera-partial3.jpg',
    similarity_score: 0.74,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-07-01T15:00:00Z',
  },

  // Content 9 발견 결과 (2건)
  {
    id: 'detected-30',
    original_content_id: 'content-9',
    detected_url: 'https://example.com/detected/venice1.jpg',
    similarity_score: 0.9,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-07-15T12:00:00Z',
  },
  {
    id: 'detected-31',
    original_content_id: 'content-9',
    detected_url: 'https://example.com/detected/venice2.jpg',
    similarity_score: 0.85,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-07-15T12:00:00Z',
  },

  // Content 11 발견 결과 (3건)
  {
    id: 'detected-32',
    original_content_id: 'content-11',
    detected_url: 'https://example.com/detected/sagrada1.jpg',
    similarity_score: 0.95,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-08-10T11:00:00Z',
  },
  {
    id: 'detected-33',
    original_content_id: 'content-11',
    detected_url: 'https://example.com/detected/sagrada2.jpg',
    similarity_score: 0.92,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-08-10T11:00:00Z',
  },
  {
    id: 'detected-34',
    original_content_id: 'content-11',
    detected_url: 'https://example.com/detected/sagrada-partial1.jpg',
    similarity_score: 0.8,
    detection_type: 'partial',
    review_status: 'pending',
    detected_at: '2025-08-10T11:00:00Z',
  },

  // Content 12 발견 결과 (1건)
  {
    id: 'detected-35',
    original_content_id: 'content-12',
    detected_url: 'https://example.com/detected/prague1.jpg',
    similarity_score: 0.87,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-09-05T13:45:00Z',
  },

  // Content 14 발견 결과 (1건)
  {
    id: 'detected-36',
    original_content_id: 'content-14',
    detected_url: 'https://example.com/detected/phone1.jpg',
    similarity_score: 0.91,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-05-25T10:00:00Z',
  },

  // Content 17 발견 결과 (2건)
  {
    id: 'detected-37',
    original_content_id: 'content-17',
    detected_url: 'https://example.com/detected/watch1.jpg',
    similarity_score: 0.93,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-07-20T10:30:00Z',
  },
  {
    id: 'detected-38',
    original_content_id: 'content-17',
    detected_url: 'https://example.com/detected/watch2.jpg',
    similarity_score: 0.89,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-07-20T10:30:00Z',
  },

  // Content 19 발견 결과 (1건)
  {
    id: 'detected-39',
    original_content_id: 'content-19',
    detected_url: 'https://example.com/detected/tablet1.jpg',
    similarity_score: 0.88,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-09-10T11:30:00Z',
  },

  // Content 22 발견 결과 (1건)
  {
    id: 'detected-40',
    original_content_id: 'content-22',
    detected_url: 'https://example.com/detected/poster1.jpg',
    similarity_score: 0.86,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-04-20T14:45:00Z',
  },

  // Content 26 발견 결과 (2건)
  {
    id: 'detected-41',
    original_content_id: 'content-26',
    detected_url: 'https://example.com/detected/event1.jpg',
    similarity_score: 0.89,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-06-25T16:45:00Z',
  },
  {
    id: 'detected-42',
    original_content_id: 'content-26',
    detected_url: 'https://example.com/detected/event2.jpg',
    similarity_score: 0.84,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-06-25T16:45:00Z',
  },

  // Content 27 발견 결과 (1건)
  {
    id: 'detected-43',
    original_content_id: 'content-27',
    detected_url: 'https://example.com/detected/launch1.jpg',
    similarity_score: 0.9,
    detection_type: 'full',
    review_status: 'pending',
    detected_at: '2025-08-30T11:00:00Z',
  },
]
