import { DetectedContent } from '@/types'

export const mockDetectedContents: DetectedContent[] = [
  // Content 1 발견 결과 (3건)
  {
    id: 'detected-1',
    content_id: 'content-1',
    source_url: 'https://example.com/blog/jeju-seongsan',
    image_url: 'https://example.com/detected/seongsan1.jpg',
    page_title: '제주도 성산일출봉 여행 후기',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-06T09:00:00Z',
    created_at: '2025-03-05T10:15:00Z',
  },
  {
    id: 'detected-2',
    content_id: 'content-1',
    source_url: 'https://example.com/travel/jeju',
    image_url: 'https://example.com/detected/seongsan2.jpg',
    page_title: '제주 여행지 추천',
    detection_type: 'partial',
    admin_review_status: 'no_match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-06T09:10:00Z',
    created_at: '2025-03-05T10:15:00Z',
  },
  {
    id: 'detected-3',
    content_id: 'content-1',
    source_url: 'https://example.com/gallery/korea',
    image_url: 'https://example.com/detected/seongsan3.jpg',
    page_title: '한국 명소 갤러리',
    detection_type: 'similar',
    admin_review_status: 'cannot_compare',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-03-05T10:15:00Z',
  },

  // Content 2 발견 결과 (5건)
  {
    id: 'detected-4',
    content_id: 'content-2',
    source_url: 'https://example.com/beach/haeundae',
    image_url: 'https://example.com/detected/beach1.jpg',
    page_title: '해운대 해수욕장',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-08T16:00:00Z',
    created_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-5',
    content_id: 'content-2',
    source_url: 'https://example.com/busan/attractions',
    image_url: 'https://example.com/detected/beach2.jpg',
    page_title: '부산 관광명소',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-03-08T16:05:00Z',
    created_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-6',
    content_id: 'content-2',
    source_url: null,
    image_url: 'https://example.com/detected/beach3.jpg',
    page_title: null,
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-7',
    content_id: 'content-2',
    source_url: 'https://example.com/photos/korea',
    image_url: 'https://example.com/detected/beach-partial1.jpg',
    page_title: '한국 사진 모음',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-03-08T15:00:00Z',
  },
  {
    id: 'detected-8',
    content_id: 'content-2',
    source_url: 'https://example.com/summer/beach',
    image_url: 'https://example.com/detected/beach-partial2.jpg',
    page_title: '여름 해변 추천',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-03-08T15:00:00Z',
  },

  // Content 3 발견 결과 (1건)
  {
    id: 'detected-9',
    content_id: 'content-3',
    source_url: 'https://example.com/temple/bulguksa',
    image_url: 'https://example.com/detected/temple1.jpg',
    page_title: '불국사 사계절',
    detection_type: 'full',
    admin_review_status: 'no_match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-04-13T10:00:00Z',
    created_at: '2025-04-12T11:30:00Z',
  },

  // Content 4 발견 결과 (8건)
  {
    id: 'detected-10',
    content_id: 'content-4',
    source_url: 'https://example.com/paris/eiffel',
    image_url: 'https://example.com/detected/eiffel1.jpg',
    page_title: 'Eiffel Tower at Night',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-21T09:00:00Z',
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-11',
    content_id: 'content-4',
    source_url: 'https://example.com/travel/paris',
    image_url: 'https://example.com/detected/eiffel2.jpg',
    page_title: 'Paris Travel Guide',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-21T09:05:00Z',
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-12',
    content_id: 'content-4',
    source_url: null,
    image_url: 'https://example.com/detected/eiffel3.jpg',
    page_title: null,
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-13',
    content_id: 'content-4',
    source_url: 'https://example.com/europe/landmarks',
    image_url: 'https://example.com/detected/eiffel4.jpg',
    page_title: 'European Landmarks',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-14',
    content_id: 'content-4',
    source_url: 'https://example.com/photos/france',
    image_url: 'https://example.com/detected/eiffel-partial1.jpg',
    page_title: 'France Photography',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-15',
    content_id: 'content-4',
    source_url: 'https://example.com/city/paris',
    image_url: 'https://example.com/detected/eiffel-partial2.jpg',
    page_title: 'Paris City Guide',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-16',
    content_id: 'content-4',
    source_url: null,
    image_url: 'https://example.com/detected/eiffel-partial3.jpg',
    page_title: null,
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },
  {
    id: 'detected-17',
    content_id: 'content-4',
    source_url: 'https://example.com/monuments/france',
    image_url: 'https://example.com/detected/eiffel-partial4.jpg',
    page_title: 'French Monuments',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-20T17:20:00Z',
  },

  // Content 5 발견 결과 (2건)
  {
    id: 'detected-18',
    content_id: 'content-5',
    source_url: 'https://example.com/london/bigben',
    image_url: 'https://example.com/detected/bigben1.jpg',
    page_title: 'Big Ben London',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-05-22T11:30:00Z',
    created_at: '2025-05-22T10:45:00Z',
  },
  {
    id: 'detected-19',
    content_id: 'content-5',
    source_url: 'https://example.com/uk/landmarks',
    image_url: 'https://example.com/detected/bigben2.jpg',
    page_title: 'UK Landmarks Collection',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-22T10:45:00Z',
  },

  // Content 7 발견 결과 (4건)
  {
    id: 'detected-20',
    content_id: 'content-7',
    source_url: 'https://example.com/tokyo/skytree',
    image_url: 'https://example.com/detected/skytree1.jpg',
    page_title: 'Tokyo Skytree Views',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-21',
    content_id: 'content-7',
    source_url: null,
    image_url: 'https://example.com/detected/skytree2.jpg',
    page_title: null,
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-22',
    content_id: 'content-7',
    source_url: 'https://example.com/japan/travel',
    image_url: 'https://example.com/detected/skytree-partial1.jpg',
    page_title: 'Japan Travel Guide',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-15T09:45:00Z',
  },
  {
    id: 'detected-23',
    content_id: 'content-7',
    source_url: 'https://example.com/asia/cities',
    image_url: 'https://example.com/detected/skytree-partial2.jpg',
    page_title: 'Asian Cities Photography',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-15T09:45:00Z',
  },

  // Content 8 발견 결과 (6건)
  {
    id: 'detected-24',
    content_id: 'content-8',
    source_url: 'https://example.com/sydney/opera',
    image_url: 'https://example.com/detected/opera1.jpg',
    page_title: 'Sydney Opera House',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-07-02T10:00:00Z',
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-25',
    content_id: 'content-8',
    source_url: 'https://example.com/australia/landmarks',
    image_url: 'https://example.com/detected/opera2.jpg',
    page_title: 'Australian Landmarks',
    detection_type: 'full',
    admin_review_status: 'match',
    reviewed_by: 'user-2',
    reviewed_at: '2025-07-02T10:05:00Z',
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-26',
    content_id: 'content-8',
    source_url: null,
    image_url: 'https://example.com/detected/opera3.jpg',
    page_title: null,
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-27',
    content_id: 'content-8',
    source_url: 'https://example.com/travel/oceania',
    image_url: 'https://example.com/detected/opera-partial1.jpg',
    page_title: 'Oceania Travel',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-28',
    content_id: 'content-8',
    source_url: 'https://example.com/architecture/modern',
    image_url: 'https://example.com/detected/opera-partial2.jpg',
    page_title: 'Modern Architecture',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'detected-29',
    content_id: 'content-8',
    source_url: 'https://example.com/photos/sydney',
    image_url: 'https://example.com/detected/opera-partial3.jpg',
    page_title: 'Sydney Photography',
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-01T15:00:00Z',
  },

  // Content 9 발견 결과 (2건)
  {
    id: 'detected-30',
    content_id: 'content-9',
    source_url: 'https://example.com/venice/canals',
    image_url: 'https://example.com/detected/venice1.jpg',
    page_title: 'Venice Grand Canal',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-15T12:00:00Z',
  },
  {
    id: 'detected-31',
    content_id: 'content-9',
    source_url: 'https://example.com/italy/travel',
    image_url: 'https://example.com/detected/venice2.jpg',
    page_title: 'Italy Travel Guide',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-15T12:00:00Z',
  },

  // Content 11 발견 결과 (3건)
  {
    id: 'detected-32',
    content_id: 'content-11',
    source_url: 'https://example.com/barcelona/sagrada',
    image_url: 'https://example.com/detected/sagrada1.jpg',
    page_title: 'Sagrada Familia Barcelona',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-08-10T11:00:00Z',
  },
  {
    id: 'detected-33',
    content_id: 'content-11',
    source_url: 'https://example.com/spain/architecture',
    image_url: 'https://example.com/detected/sagrada2.jpg',
    page_title: 'Spanish Architecture',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-08-10T11:00:00Z',
  },
  {
    id: 'detected-34',
    content_id: 'content-11',
    source_url: null,
    image_url: 'https://example.com/detected/sagrada-partial1.jpg',
    page_title: null,
    detection_type: 'partial',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-08-10T11:00:00Z',
  },

  // Content 12 발견 결과 (1건)
  {
    id: 'detected-35',
    content_id: 'content-12',
    source_url: 'https://example.com/prague/castle',
    image_url: 'https://example.com/detected/prague1.jpg',
    page_title: 'Prague Castle Views',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-09-05T13:45:00Z',
  },

  // Content 14 발견 결과 (1건)
  {
    id: 'detected-36',
    content_id: 'content-14',
    source_url: 'https://example.com/tech/smartphones',
    image_url: 'https://example.com/detected/phone1.jpg',
    page_title: 'Latest Smartphones 2025',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-05-25T10:00:00Z',
  },

  // Content 17 발견 결과 (2건)
  {
    id: 'detected-37',
    content_id: 'content-17',
    source_url: 'https://example.com/wearables/smartwatch',
    image_url: 'https://example.com/detected/watch1.jpg',
    page_title: 'Best Smartwatches 2025',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-20T10:30:00Z',
  },
  {
    id: 'detected-38',
    content_id: 'content-17',
    source_url: 'https://example.com/tech/reviews',
    image_url: 'https://example.com/detected/watch2.jpg',
    page_title: 'Tech Product Reviews',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-07-20T10:30:00Z',
  },

  // Content 19 발견 결과 (1건)
  {
    id: 'detected-39',
    content_id: 'content-19',
    source_url: 'https://example.com/tablets/review',
    image_url: 'https://example.com/detected/tablet1.jpg',
    page_title: 'Tablet Reviews',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-09-10T11:30:00Z',
  },

  // Content 22 발견 결과 (1건)
  {
    id: 'detected-40',
    content_id: 'content-22',
    source_url: 'https://example.com/design/posters',
    image_url: 'https://example.com/detected/poster1.jpg',
    page_title: 'Poster Design Gallery',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-04-20T14:45:00Z',
  },

  // Content 26 발견 결과 (2건)
  {
    id: 'detected-41',
    content_id: 'content-26',
    source_url: 'https://example.com/events/anniversary',
    image_url: 'https://example.com/detected/event1.jpg',
    page_title: 'Anniversary Event Photos',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-25T16:45:00Z',
  },
  {
    id: 'detected-42',
    content_id: 'content-26',
    source_url: 'https://example.com/photos/events',
    image_url: 'https://example.com/detected/event2.jpg',
    page_title: 'Event Photography',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-06-25T16:45:00Z',
  },

  // Content 27 발견 결과 (1건)
  {
    id: 'detected-43',
    content_id: 'content-27',
    source_url: 'https://example.com/products/launch',
    image_url: 'https://example.com/detected/launch1.jpg',
    page_title: 'Product Launch Event',
    detection_type: 'full',
    admin_review_status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2025-08-30T11:00:00Z',
  },
]
